### PR TITLE
Use Rollup for bundling

### PR DESCRIPTION
**Pull request by Turbo87**
Instead of just concatenating the files use ES6 modules and bundle them together using http://rollupjs.org/

This PR also improves performance a little by attaching the methods to the prototypes instead of recreating them in every constructor

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like rollup doesn't work on Node 0.x though... :-/

**Comment by Turbo87** [comment]
Looks like we can use Node 6 for running rollup and then use the original Node version to test the output.

**Comment by edi9999** [comment]
I would still like to generate the browser.js file (previously in the npm run complie:browser script).

So that the demo at https://github.com/edi9999/jsqrcode/blob/master/examples/browser-upload/index.html still works.

**Comment by edi9999** [comment]
oh I see that you have changed the index.html too

**Comment by edi9999** [comment]
Nice work @Turbo87 !

**Comment by edi9999** [comment]
Oops, the readme is out of sync by merging ...

**Comment by Turbo87** [comment]
@edi9999 sorry, forgot about the readme. are you planning for a new NPM release in the near future?

**Comment by edi9999** [comment]
Yes, but not before Monday, I don't have a computer until than

**Comment by edi9999** [comment]
I will notify you when it is released.

**Comment by edi9999** [comment]
Released in 0.2.2 on npm

**Pull request merged**
