### PR TITLE
Add HTML example, add webpack build step, optimize existing build steps

### PR DESCRIPTION
**Pull request by backflip**
Hey Edgar, thanks a lot for this fork!

Would you consider adding this very basic browser example? While preparing it, I took the liberty of adding an additional Gulp taks using webpack to generate a build for the browser. This should make it easier for many users to generate the browser build since they don't have to globally install browserify, e.g.

Additionally, I have added npm scripts triggering the gulp tasks and "localized" some variables which ended up polluting the global scope.

### CODE REVIEW

**Comment by backflip** [comment]
Demo: https://qrcode-reader-eftpscijbb.now.sh/examples/browser-upload/

**Comment by edi9999** [comment]
Hi, thanks for submitting this PR.

One thing doesn't seem totally ok : 

The compile script shouldn't be triggered on post install, but rather on prepublish.

**Comment by backflip** [comment]
Ah, so would you want to publish the compiled scripts, too? Sounds good to me.

**Comment by edi9999** [comment]
Yes

**Comment by backflip** [comment]
Okay, I have updated the `package.json` and `README.md` accordingly.
In addition, I have created a `.npmignore`. It corresponds to `.gitignore` but does *not* contain `dist/`so npm can publish it (without an `.npmignore` it would apparently [use the `.gitignore` file](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package))

**Comment by edi9999** [comment]
Merged, Thanks a lot for contributing ! I'm publishing npm version 0.1.1

**Pull request merged**
