### PR TITLE
Test code cleanup

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by edi9999** [comment]
Hi, I prefer not to use the PNG.load method, but rather be explicit that we are reading the buffer from the filesystem

**Comment by edi9999** [comment]
I think it would make sense to use eslint or something similar for that.

**Comment by Turbo87** [comment]
@edi9999 I have a branch here that introduces ESLint, but I wanted to get the other stuff merged first ;)

**Comment by edi9999** [comment]
Ok, please remove the PNG.load calls

**Comment by Turbo87** [comment]
@edi9999 done

**Comment by edi9999** [comment]
Thanks !

**Pull request merged**
