### PR TITLE
Add ESLint support

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by edi9999** [comment]
Thanks. I'd like to keep the automated tests on v0.10.

Eslint 3.x is incompatible with node <4, so i would write in package.json :

https://www.npmjs.com/package/node-version-check

  "lint": "node-version-check \">=4\" && eslint . || node-version-check \"<4\""

**Comment by Turbo87** [comment]
> Thanks. I'd like to keep the automated tests on v0.10.
> 
> Eslint 3.x is incompatible with node <4

That's why I've used ESLint 2.x for now which still runs on Node 0.10 and above

**Comment by edi9999** [comment]
Yes but you've removed 0.10 from the .travis.yml

I'd like at least 0.10, 0.12, 4,6

**Comment by Turbo87** [comment]
> I'd like at least 0.10, 0.12, 4,6

which is exactly what I did in https://github.com/edi9999/jsqrcode/pull/25/commits/cf5378221b0f772025f1a58ca0acc1051f50e1c4

**Comment by edi9999** [comment]
Oh sorry, I misread the diff.

Thank we can merge.

Thanks a lot for the contribution !!

**Pull request merged**
