### PR TITLE
Update callback to be error-first

### PR DESCRIPTION
**Pull request by noahbass**
It would be great if the callback for the reader conformed to the javascript error-first convention.

So `qr.callback = function(result, error) { /* ... */ }` would become `qr.callback = function(error, result) { /* ... */ }`

### CODE REVIEW

**Comment by edi9999** [comment]
Thanks, indeed, error first callbacks have been a standard since the beginning in Node. However, this is a major API change, and would also require a major version change. I will keep this MR for a while, and merge it when we can say we're ready for version 1.0

**Comment by edi9999** [comment]
Can you please create a CHANGELOG file so that users will know what changed from 0.x and 1.x ?

**Comment by noahbass** [comment]
Added a changelog! I tried to stick to the guidelines at [keepachangelog.com](http://keepachangelog.com/), but it's a very bare changelog at the moment.

**Comment by edi9999** [comment]
Thanks !

**Comment by rugk** [comment]
Any news?

**Comment by edi9999** [comment]
Merged into a new branch called `v1`

**Comment by safeeeralshooog** [comment]
hcthgu gf6i

**Pull request merged**
